### PR TITLE
Update to 1.0.0b3

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

fixes #22

### CODE REVIEW

**Comment by dhirschfeld** [comment]
I need this version over at https://github.com/conda-forge/staged-recipes/pull/6893

I wasn't sure if it's ok to publish a beta version but since [`marshmallow`](https://github.com/conda-forge/marshmallow-feedstock/blob/master/recipe/meta.yaml#L2) seems to I figure it might be ok?  `¯\_(ツ)_/¯`

**Comment by carlodri** [comment]
I think it is not a good idea to mix stable and pre-release versions. I would rather create a `1.0.0b` branch in the main feedstock for this pre-release version (like [here](https://conda-forge.org/docs/conda-forge_gotchas.html#using-a-fork-vs-a-branch-when-updating-a-recipe). I've never done it before, but I think it's just a matter of creating the branch and PRing towards it. 

@conda-forge/core any suggestions/observations?

**Comment by isuruf** [comment]
You can add the following,
```yaml
channel_targets:
- conda-forge dev
```
to `recipe/conda_build_config.yaml` and then rerender to configure the branch to upload to `conda-forge/label/dev`. You can then push it to a branch.

**Comment by carlodri** [comment]
thanks @isuruf! Then do we need any special syntax to use this `dev` version in the requirements of another feedstock? Or we just say `apispec >=1.0.0b1`?

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by carlodri** [comment]
thanks @dhirschfeld. Shall we name the branch `1.0.0b`?

**Comment by dhirschfeld** [comment]
@carlodri - are you happy to publish a beta to the dev label?

@isuruf is this what you meant? Also, is there some way to get the `responder` feedstock to use the `conda-forge/label/dev` label?

**Comment by carlodri** [comment]
> are you happy to publish a beta to the dev label?

sure, ok for me. I just wanted to understand how to pick a package with that label from the requirements of another feedstock (as you were asking too).

**Comment by dhirschfeld** [comment]
I'm working on the assumption that putting:
```yaml
channel_sources:
  - conda-forge,conda-forge dev,defaults
```
...in the `responder` `conda_build_config.yaml` should work. In any case, my plan is to try it and find out!

**Comment by dhirschfeld** [comment]
@carlodri - I'm not sure what you mean by naming the branch `1.0.0b`? You mean I should create a `1.0.0b` branch in this repo and then open a new PR to request my `patch-1` branch be merged into that rather than `master`?

I'm not sure that that's necessary? Or even if it would work? In any case, I can't create a new branch here since I'm not a maintainer. I'm happy to do so if you want but you'll have to create the branch for me AFAICS.

**Comment by dhirschfeld** [comment]
I *think* this is good to go as-is though. IIUC if we merge this it will publish `1.0.0b3` to the `dev` label after which we can then figure out what needs to be done in the `responder` recipe to use the `dev` label.

If we do stuff this up and publish a pre-release to the main channel I'm sure conda-forge admin will oblige by nuking the build for us (applying the [EAFP](https://blogs.msdn.microsoft.com/pythonengineering/2016/06/29/idiomatic-python-eafp-versus-lbyl/) principal)

**Comment by carlodri** [comment]
I'm not sure. AFAIU for cleanness we should keep the `master` branch for the stable releases and we make this new branch which labels builds as `dev`. This is what @isuruf was saying above, if I understood him correctly (can you confirm us @isuruf?).

**Comment by dhirschfeld** [comment]
> *we make this new branch which labels builds as `dev`*

If this will work / is the way to go, I'd suggest just a single extra branch called `dev` where we can publish *all* pre-releases.

I might have to leave it to you though as it's bedtime here. I'm happy to pick it up in the morning though...

**Comment by carlodri** [comment]
judging from here: https://github.com/conda-forge/gmt-feedstock/issues/9 and some other googling, making a `dev` branch seems like a good way. 

I just want to make sure that we don't get stuck in the requirements of the downstream feedstock, _i.e._ there might currently be no way to point the recipe requirements to the `dev` label...

ok I'll make sure of this stuff and leave you some follow-up here! Good night!

**Comment by dhirschfeld** [comment]
If you want to go ahead and create a `dev` branch I can open another PR against that and then you can choose which (if either) to merge.

As a maintainer you should be able to do it from the GitHub UI:
image

**Comment by carlodri** [comment]
No, this PR is fine. In case I need it, as a maintainer, I can edit this PRs destination branch.

**Comment by carlodri** [comment]
let's hope I didn't 🔥 conda-forge... 😀

**Pull request merged**
